import { getPayload } from 'payload'
import config from '@payload-config'

import type { Category, Doc } from '../payload-types'

/**
 * One node of the docs category tree.
 *
 * `url` is derived from the ancestor slug chain during the tree walk rather than
 * from the Nested Docs plugin's `breadcrumbs`, which can be stale while an editor
 * is mid-edit (breadcrumbs are regenerated by an afterChange hook, so a renamed
 * ancestor leaves descendants pointing at the old path until they are re-saved).
 *
 * `articleCount` includes the descendants' articles, not just the node's own.
 */
export type CategoryNode = {
  id: number
  title: string
  slug: string
  url: string
  order: number
  articleCount: number
  children: CategoryNode[]
}

/** Relationship fields are `number | Doc`; at depth 0 they are always the id. */
const relationId = (value: unknown): number | null => {
  if (typeof value === 'number') return value
  if (value && typeof value === 'object' && 'id' in value) {
    const id = (value as { id?: unknown }).id
    return typeof id === 'number' ? id : null
  }
  return null
}

const segment = (slug?: string | null): string => (slug ?? '').replace(/^\/+|\/+$/g, '')

const resolveTenantId = async (tenantSlug: string): Promise<number | null> => {
  const payload = await getPayload({ config })

  const tenants = await payload.find({
    collection: 'tenants',
    where: { slug: { equals: tenantSlug } },
    limit: 1,
    depth: 0,
  })

  const tenant = tenants.docs[0]
  return tenant ? tenant.id : null
}

/**
 * Every category for the tenant, in one query. `limit: 0` returns all of them and
 * `depth: 0` keeps `parent` a plain id so no relationship population happens —
 * both matter at 150+ categories.
 */
const fetchCategories = async (tenantId: number | null): Promise<Category[]> => {
  const payload = await getPayload({ config })

  const result = await payload.find({
    collection: 'categories',
    where: tenantId === null ? {} : { tenant: { equals: tenantId } },
    limit: 0,
    depth: 0,
    sort: 'order',
  })

  return result.docs ?? []
}

/**
 * Article totals per category id, in one query. Only the `category` field is
 * selected, so this stays cheap even with several thousand articles.
 */
const fetchOwnArticleCounts = async (tenantId: number | null): Promise<Map<number, number>> => {
  const payload = await getPayload({ config })

  const result = await payload.find({
    collection: 'docs',
    where: tenantId === null ? {} : { tenant: { equals: tenantId } },
    limit: 0,
    depth: 0,
    sort: 'id',
    select: { category: true },
  })

  const counts = new Map<number, number>()

  for (const doc of result.docs ?? []) {
    const categoryId = relationId(doc.category)
    if (categoryId === null) continue
    counts.set(categoryId, (counts.get(categoryId) ?? 0) + 1)
  }

  return counts
}

/**
 * Assemble the flat, `order`-sorted list into a tree in a single pass.
 *
 * Two linear passes over the array and Map lookups only — never a query per
 * node, which is what falls over once a tenant has 150 categories.
 */
const buildTree = (categories: Category[], ownCounts: Map<number, number>): CategoryNode[] => {
  const nodes = new Map<number, CategoryNode>()

  // Pass 1: a node per category. `url` is filled in during the walk below.
  for (const category of categories) {
    nodes.set(category.id, {
      id: category.id,
      title: category.title ?? '',
      slug: segment(category.slug),
      url: '',
      order: category.order ?? 0,
      articleCount: ownCounts.get(category.id) ?? 0,
      children: [],
    })
  }

  // Pass 2: attach each node to its parent. The source array is already sorted
  // by `order`, so siblings land in the right sequence as they are pushed.
  const roots: CategoryNode[] = []

  for (const category of categories) {
    const node = nodes.get(category.id)
    if (!node) continue

    const parentId = relationId(category.parent)
    const parent = parentId === null ? undefined : nodes.get(parentId)

    // A missing or self-referencing parent (deleted ancestor, bad import) is
    // promoted to a root rather than being dropped out of the navigation.
    if (parent && parent !== node) {
      parent.children.push(node)
    } else {
      roots.push(node)
    }
  }

  // Walk once to stamp urls from the ancestor chain and roll counts upward.
  // Iterative post-order so a pathological depth cannot blow the call stack.
  type Frame = { node: CategoryNode; prefix: string; visited: boolean }
  const stack: Frame[] = []
  const seen = new Set<number>()

  for (let i = roots.length - 1; i >= 0; i -= 1) {
    stack.push({ node: roots[i], prefix: '', visited: false })
  }

  while (stack.length > 0) {
    const frame = stack.pop() as Frame
    const { node, prefix } = frame

    if (frame.visited) {
      for (const child of node.children) node.articleCount += child.articleCount
      continue
    }

    // Cycle guard: a parent loop would otherwise recurse forever.
    if (seen.has(node.id)) {
      node.children = []
      node.url = node.url || `${prefix}/${node.slug}`
      continue
    }
    seen.add(node.id)

    node.url = node.slug ? `${prefix}/${node.slug}` : prefix || '/'

    frame.visited = true
    stack.push(frame)

    for (let i = node.children.length - 1; i >= 0; i -= 1) {
      stack.push({ node: node.children[i], prefix: node.url, visited: false })
    }
  }

  return roots
}

/**
 * The full category tree for one tenant, built from exactly three queries
 * (tenant lookup, all categories, all article category ids).
 */
export async function getDocsTree(tenantSlug: string): Promise<CategoryNode[]> {
  const tenantId = await resolveTenantId(tenantSlug)
  if (tenantId === null) return []

  const [categories, ownCounts] = await Promise.all([
    fetchCategories(tenantId),
    fetchOwnArticleCounts(tenantId),
  ])

  return buildTree(categories, ownCounts)
}

/** Depth-first list of every node in the tree, parents before children. */
export function flattenNodes(nodes: CategoryNode[]): CategoryNode[] {
  const out: CategoryNode[] = []
  const stack = [...nodes].reverse()
  while (stack.length) {
    const node = stack.pop() as CategoryNode
    out.push(node)
    for (let i = node.children.length - 1; i >= 0; i--) stack.push(node.children[i])
  }
  return out
}

/** Finds a node by category id, or by url when a string is passed. */
export function findNode(
  nodes: CategoryNode[],
  target: number | string,
): CategoryNode | undefined {
  return flattenNodes(nodes).find((node) =>
    typeof target === 'number' ? node.id === target : node.url === target,
  )
}

export type DocsCrumb = { label: string; url: string }

/**
 * Breadcrumb trail for an article: its category ancestors, then the article.
 * Built by walking up the `parent` chain of the tenant's categories, again from
 * a single query — and again ignoring the plugin's `breadcrumbs` field.
 */
export async function getDocsBreadcrumbs(doc: Doc): Promise<DocsCrumb[]> {
  const categoryId = relationId(doc?.category)
  const tenantId = relationId(doc?.tenant)

  const crumbs: DocsCrumb[] = []
  let parentUrl = ''

  if (categoryId !== null) {
    const categories = await fetchCategories(tenantId)
    const byId = new Map<number, Category>()
    for (const category of categories) byId.set(category.id, category)

    // Walk up to the root, guarding against a cycle in `parent`.
    const chain: Category[] = []
    const seen = new Set<number>()
    let current = byId.get(categoryId)

    while (current && !seen.has(current.id)) {
      seen.add(current.id)
      chain.unshift(current)
      const nextId = relationId(current.parent)
      current = nextId === null ? undefined : byId.get(nextId)
    }

    for (const category of chain) {
      const slug = segment(category.slug)
      if (!slug) continue
      parentUrl = `${parentUrl}/${slug}`
      crumbs.push({ label: category.title ?? slug, url: parentUrl })
    }
  }

  const docSlug = segment(doc?.slug)
  crumbs.push({
    label: doc?.title ?? docSlug,
    url: docSlug ? `${parentUrl}/${docSlug}` : parentUrl || '/',
  })

  return crumbs
}
