/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    accounts: AccountAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    accounts: Account;
    authors: Author;
    tenants: Tenant;
    media: Media;
    pages: Page;
    posts: Post;
    docs: Doc;
    categories: Category;
    partners: Partner;
    integrations: Integration;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'pages' | 'posts' | 'docs';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    docs: DocsSelect<false> | DocsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Account;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface AccountAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('super-admin' | 'editor')[];
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Path segment used for routing: main, docs, partners
   */
  slug: string;
  /**
   * Public domain for this property, e.g. docs.qualiware.com
   */
  domain?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  fullName: string;
  /**
   * What this person is entitled to see. Both is valid — a partner who also holds a licence.
   */
  audiences: ('customer' | 'partner')[];
  /**
   * Customer organisation. Used for ticket attribution, so staff only — a self-editable value here is an impersonation route.
   */
  organisation?: string | null;
  /**
   * Set when this person works for a partner. Drives the partner directory link.
   */
  partner?: (number | null) | Partner;
  /**
   * Zoho Desk contact id — the authoritative support identity. Set during onboarding. Never derived from anything the user can type.
   */
  zohoContactId?: string | null;
  /**
   * DISPLAY ONLY, and not authoritative. The contract in Zoho Desk decides the real SLA — never compute entitlement from this field.
   */
  supportTierHint?: ('standard' | 'enhanced' | 'premium') | null;
  updatedAt: string;
  createdAt: string;
  /**
   * Login credential and the link to the Zoho Desk contact. Changing it re-points support history — staff only.
   */
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'accounts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  logo?: {
    media?: (number | null) | Media;
    placeholder?: string | null;
  };
  partnerType: 'technology' | 'solution';
  tier?: ('silver' | 'gold' | 'platinum') | null;
  region?: ('nordics' | 'europe' | 'north-america' | 'mea' | 'apac' | 'global') | null;
  industries?:
    | ('public-sector' | 'finance' | 'defence' | 'energy' | 'manufacturing' | 'life-sciences' | 'cross-industry')[]
    | null;
  /**
   * Short description for directory cards
   */
  blurb?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  website?: string | null;
  contactEmail?: string | null;
  services?:
    | {
        name?: string | null;
        scope?: string | null;
        id?: string | null;
      }[]
    | null;
  atAGlance?: {
    certifiedConsultants?: number | null;
    partnerSince?: string | null;
    languages?: string | null;
  };
  quote?: {
    text?: string | null;
    attribution?: string | null;
  };
  integrations?: (number | Integration)[] | null;
  caseStudies?: (number | Page)[] | null;
  /**
   * End customers this partner may raise cases for. Mirrors the contract in Zoho Desk — Zoho remains authoritative.
   */
  supportedCustomers?:
    | {
        customerName: string;
        /**
         * "None" means QualiWare does not provide support for this customer. The case form says so plainly.
         */
        supportLevelSold: 'none' | 'standard' | 'enhanced' | 'premium';
        /**
         * Zoho Desk account id for this end customer, once known
         */
        zohoAccountId?: string | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  logo?: {
    media?: (number | null) | Media;
    placeholder?: string | null;
  };
  builtBy: 'qualiware' | 'partner';
  /**
   * The partner that builds and maintains this integration
   */
  partner?: (number | null) | Partner;
  /**
   * Drives the roadmap view. Only "Available now" is presented as something you can use today.
   */
  status: 'available' | 'inDevelopment' | 'planned' | 'retired';
  /**
   * Deliberately vague, e.g. "H1 2027". Never commit to a date the roadmap cannot hold.
   */
  expectedAvailability?: string | null;
  category?: ('itsm' | 'identity' | 'data' | 'collaboration' | 'devops' | 'grc') | null;
  summary?: string | null;
  /**
   * Deep link into docs.qualiware.com — how to authenticate lives in Docs
   */
  docsUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * Full path without a leading slash, e.g. "solutions/nis2". Use "home" for the property root.
   */
  slug: string;
  /**
   * Set automatically from the slug.
   */
  section?:
    | (
        | 'home'
        | 'platform'
        | 'solutions'
        | 'resources'
        | 'customers'
        | 'company'
        | 'legal'
        | 'partners'
        | 'support'
        | 'other'
      )
    | null;
  /**
   * Leave empty for public — the default, and right for almost everything. Listing an audience restricts this to signed-in accounts holding it, and removes it from search engines.
   */
  audiences?: ('customer' | 'partner')[] | null;
  /**
   * Choose this FIRST. On a new page it builds the right blocks in the right order, already styled — you then replace the placeholder text. It also decides the page’s look, so the styling options inside blocks are hidden.
   */
  pageType?:
    | (
        | 'standard'
        | 'caseStudy'
        | 'platformCapability'
        | 'solutionDiscipline'
        | 'solutionIndustry'
        | 'solutionRegulation'
        | 'resourceHub'
        | 'company'
        | 'legal'
      )
    | null;
  /**
   * Search and social metadata
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  /**
   * Experience, Expertise, Authoritativeness, Trustworthiness. Who stands behind this page, and when it was last checked.
   */
  authorship?: {
    /**
     * Who wrote this. Manage the person in the Authors collection — name, role and credentials all come from there.
     */
    author?: (number | null) | Author;
    /**
     * Subject-matter reviewer, shown as "Reviewed by". Required in practice on regulation pages, which carry legal consequence.
     */
    reviewer?: (number | null) | Author;
    /**
     * Shown on the page. Regulation pages should be re-reviewed regularly.
     */
    lastReviewed?: string | null;
    /**
     * First-hand experience signal, e.g. "Based on 40+ NIS2 scoping engagements since 2023."
     */
    experienceNote?: string | null;
  };
  /**
   * Citations. Every external claim, regulation reference or analyst statement needs one, with a date.
   */
  sources?:
    | {
        label: string;
        publisher?: string | null;
        url?: string | null;
        /**
         * Publication or access date, e.g. "December 2024"
         */
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  caseStudy?: {
    /**
     * Eyebrow, e.g. DEFENCE & AEROSPACE
     */
    category?: string | null;
    summary?: string | null;
    image?: {
      media?: (number | null) | Media;
      placeholder?: string | null;
    };
  };
  /**
   * Buyers arrive with a deadline, not a discipline — lead with the facts.
   */
  regulation?: {
    /**
     * Legal instrument, e.g. "Directive (EU) 2022/2555"
     */
    instrument?: string | null;
    inForceSince?: string | null;
    /**
     * e.g. "17 October 2024"
     */
    deadline?: string | null;
    /**
     * Who is in scope
     */
    appliesTo?: string | null;
    penalty?: string | null;
    /**
     * What the regulation requires, and what must be evidenced
     */
    requirements?:
      | {
          requirement?: string | null;
          evidence?: string | null;
          /**
           * Article reference, e.g. "Art. 21(2)(a)"
           */
          article?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Solutions pages link *down* into the Platform capability pages that deliver them.
   */
  relatedCapabilities?: (number | Page)[] | null;
  /**
   * Built for you from the archetype. Replace any text in [square brackets]. Add or remove blocks only if the page genuinely needs it — the default order is the argument the page makes.
   */
  layout?:
    | (
        | HeroBlock
        | LogoWallBlock
        | GartnerCalloutBlock
        | FeatureGridBlock
        | ValuePropsBlock
        | TestimonialBlock
        | CaseStudyCardsBlock
        | CaseStudyArchiveBlock
        | ComparisonTableBlock
        | PricingTableBlock
        | CTABannerBlock
        | ResourceGridBlock
        | FormBlockBlock
      )[]
    | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who write or review content. Every field except the biography is required — an incomplete byline is worse than none.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * Full name, as it should appear in a byline
   */
  name: string;
  /**
   * Used if author profile pages are added later, e.g. "mette-holm"
   */
  slug: string;
  /**
   * e.g. "Principal Enterprise Architect, QualiWare"
   */
  role: string;
  /**
   * Short and checkable, e.g. "TOGAF 9 certified · 16 years in enterprise architecture". Kept to one line — this is a credibility signal, not a CV.
   */
  credentials: string;
  /**
   * Head-and-shoulders, real photo. Falls back to initials until one is uploaded.
   */
  photo?: (number | null) | Media;
  /**
   * Full LinkedIn profile URL. Required: an author a reader cannot verify is not much of a signal.
   */
  linkedin: string;
  /**
   * Optional. Two or three sentences on what this person actually does, for a future profile page.
   */
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  variant?: ('darkGreen' | 'iceBlue' | 'navy') | null;
  eyebrow?: string | null;
  heading: string;
  lead?: string | null;
  ctas?:
    | {
        label?: string | null;
        href?: string | null;
        style?: ('neon' | 'outline' | 'solid') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Animated platform mock panel (homepage hero)
   */
  showProductPanel?: boolean | null;
  showConstellation?: boolean | null;
  showScrollCue?: boolean | null;
  /**
   * Large search field (docs / resources hero)
   */
  showSearch?: boolean | null;
  searchPlaceholder?: string | null;
  popularSearches?:
    | {
        label?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ice-blue proof band rendered under the hero
   */
  stats?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoWallBlock".
 */
export interface LogoWallBlock {
  label?: string | null;
  logos?:
    | {
        name?: string | null;
        logo?: {
          media?: (number | null) | Media;
          /**
           * Shot brief shown while no image is uploaded
           */
          placeholder?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoWall';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GartnerCalloutBlock".
 */
export interface GartnerCalloutBlock {
  eyebrow?: string | null;
  heading?: string | null;
  lead?: string | null;
  linkLabel?: string | null;
  linkHref?: string | null;
  cards?:
    | {
        title?: string | null;
        subtitle?: string | null;
        meta?: string | null;
        id?: string | null;
      }[]
    | null;
  peerInsights?: {
    score?: string | null;
    source?: string | null;
    quote?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'gartnerCallout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  eyebrow?: string | null;
  heading?: string | null;
  features?:
    | {
        title?: string | null;
        description?: string | null;
        linkLabel?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ValuePropsBlock".
 */
export interface ValuePropsBlock {
  layout?: ('split' | 'grid') | null;
  eyebrow?: string | null;
  heading?: string | null;
  lead?: string | null;
  image?: {
    media?: (number | null) | Media;
    /**
     * Shot brief shown while no image is uploaded
     */
    placeholder?: string | null;
  };
  items?:
    | {
        title?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'valueProps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock".
 */
export interface TestimonialBlock {
  quote: string;
  name?: string | null;
  role?: string | null;
  org?: string | null;
  portrait?: {
    media?: (number | null) | Media;
    /**
     * Shot brief shown while no image is uploaded
     */
    placeholder?: string | null;
  };
  videoStill?: {
    media?: (number | null) | Media;
    /**
     * Shot brief shown while no image is uploaded
     */
    placeholder?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonial';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyCardsBlock".
 */
export interface CaseStudyCardsBlock {
  heading?: string | null;
  caseStudies?: (number | Page)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'caseStudyCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyArchiveBlock".
 */
export interface CaseStudyArchiveBlock {
  heading?: string | null;
  lead?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'caseStudyArchive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonTableBlock".
 */
export interface ComparisonTableBlock {
  heading?: string | null;
  lead?: string | null;
  /**
   * Italic sourcing note under the table
   */
  note?: string | null;
  /**
   * First vendor with "highlighted" is rendered as the QualiWare column
   */
  vendors?:
    | {
        name?: string | null;
        highlighted?: boolean | null;
        id?: string | null;
      }[]
    | null;
  rows?:
    | {
        capability?: string | null;
        /**
         * One cell per vendor, in vendor order
         */
        cells?:
          | {
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'comparisonTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingTableBlock".
 */
export interface PricingTableBlock {
  heading?: string | null;
  lead?: string | null;
  note?: string | null;
  tiers?:
    | {
        name?: string | null;
        description?: string | null;
        emphasized?: boolean | null;
        /**
         * e.g. MOST CHOSEN — shown on the emphasized card
         */
        tabLabel?: string | null;
        features?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricingTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABannerBlock".
 */
export interface CTABannerBlock {
  background?: ('iceBlue' | 'darkGreen' | 'tinted') | null;
  heading?: string | null;
  text?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResourceGridBlock".
 */
export interface ResourceGridBlock {
  heading?: string | null;
  showFilters?: boolean | null;
  items?:
    | {
        resourceType?: ('blog' | 'webinar' | 'analyst' | 'story' | 'guide' | 'newsletter') | null;
        title?: string | null;
        summary?: string | null;
        /**
         * e.g. "6 min read" or a date
         */
        meta?: string | null;
        featured?: boolean | null;
        image?: {
          media?: (number | null) | Media;
          /**
           * Shot brief shown while no image is uploaded
           */
          placeholder?: string | null;
        };
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'resourceGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlockBlock".
 */
export interface FormBlockBlock {
  eyebrow?: string | null;
  heading?: string | null;
  lead?: string | null;
  /**
   * Arrow-bulleted promises shown beside the form
   */
  expectations?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ice-blue quote panel beside the form
   */
  sideQuote?: string | null;
  formFields?:
    | {
        label?: string | null;
        name?: string | null;
        fieldType?: ('text' | 'email' | 'select' | 'textarea' | 'chips') | null;
        options?:
          | {
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        required?: boolean | null;
        width?: ('half' | 'full') | null;
        id?: string | null;
      }[]
    | null;
  submitLabel?: string | null;
  privacyNote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'pages';
          value: number | Page;
        }
      | {
          relationTo?: 'posts';
          value: number | Post;
        }
      | {
          relationTo?: 'docs';
          value: number | Doc;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: ('pages' | 'posts' | 'docs')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog articles, webinars, guides and analyst research. Customer stories are Pages, not Posts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * The last part of the URL only, e.g. "who-owns-the-model". The type decides the rest.
   */
  slug: string;
  /**
   * Leave empty for public — the default, and right for almost everything. Listing an audience restricts this to signed-in accounts holding it, and removes it from search engines.
   */
  audiences?: ('customer' | 'partner')[] | null;
  /**
   * Decides the URL and which hub pages this appears on.
   */
  postType: 'blog' | 'webinar' | 'guide' | 'analystResearch';
  /**
   * Sorts the listings. Newest first.
   */
  publishedAt: string;
  /**
   * Shown as the byline. Manage the person in Authors.
   */
  author?: (number | null) | Author;
  /**
   * One or two sentences. Shown on every card that links here.
   */
  summary: string;
  image?: {
    media?: (number | null) | Media;
    /**
     * Shot brief, shown while no image is uploaded
     */
    placeholder?: string | null;
  };
  /**
   * Practical detail shown on the card
   */
  meta?: {
    /**
     * e.g. "6 min read"
     */
    readTime?: string | null;
    /**
     * e.g. "45 minutes"
     */
    duration?: string | null;
    /**
     * Already recorded, rather than upcoming
     */
    onDemand?: boolean | null;
  };
  /**
   * Shown large at the top of its hub page. Use sparingly.
   */
  featured?: boolean | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs".
 */
export interface Doc {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  categoryPath?: string | null;
  /**
   * Where this article lives in the docs navigation tree
   */
  category?: (number | null) | Category;
  /**
   * Manual sort within the category
   */
  order?: number | null;
  /**
   * Leave empty for public — the default, and right for almost everything. Listing an audience restricts this to signed-in accounts holding it, and removes it from search engines.
   */
  audiences?: ('customer' | 'partner')[] | null;
  /**
   * e.g. "10.8 and later"
   */
  appliesTo?: string | null;
  excerpt?: string | null;
  searchText?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  parent?: (number | null) | Doc;
  breadcrumbs?:
    | {
        doc?: (number | null) | Doc;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  /**
   * Manual sort order within a sibling level — all docs-nav queries sort by this.
   */
  order?: number | null;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  formName?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'docs';
        value: number | Doc;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'integrations';
        value: number | Integration;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'accounts';
        value: number | Account;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'accounts';
        value: number | Account;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  fullName?: T;
  audiences?: T;
  organisation?: T;
  partner?: T;
  zohoContactId?: T;
  supportTierHint?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  credentials?: T;
  photo?: T;
  linkedin?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  section?: T;
  audiences?: T;
  pageType?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  authorship?:
    | T
    | {
        author?: T;
        reviewer?: T;
        lastReviewed?: T;
        experienceNote?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        publisher?: T;
        url?: T;
        date?: T;
        id?: T;
      };
  caseStudy?:
    | T
    | {
        category?: T;
        summary?: T;
        image?:
          | T
          | {
              media?: T;
              placeholder?: T;
            };
      };
  regulation?:
    | T
    | {
        instrument?: T;
        inForceSince?: T;
        deadline?: T;
        appliesTo?: T;
        penalty?: T;
        requirements?:
          | T
          | {
              requirement?: T;
              evidence?: T;
              article?: T;
              id?: T;
            };
      };
  relatedCapabilities?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        logoWall?: T | LogoWallBlockSelect<T>;
        gartnerCallout?: T | GartnerCalloutBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        valueProps?: T | ValuePropsBlockSelect<T>;
        testimonial?: T | TestimonialBlockSelect<T>;
        caseStudyCards?: T | CaseStudyCardsBlockSelect<T>;
        caseStudyArchive?: T | CaseStudyArchiveBlockSelect<T>;
        comparisonTable?: T | ComparisonTableBlockSelect<T>;
        pricingTable?: T | PricingTableBlockSelect<T>;
        ctaBanner?: T | CTABannerBlockSelect<T>;
        resourceGrid?: T | ResourceGridBlockSelect<T>;
        formBlock?: T | FormBlockBlockSelect<T>;
      };
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  heading?: T;
  lead?: T;
  ctas?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
        id?: T;
      };
  showProductPanel?: T;
  showConstellation?: T;
  showScrollCue?: T;
  showSearch?: T;
  searchPlaceholder?: T;
  popularSearches?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoWallBlock_select".
 */
export interface LogoWallBlockSelect<T extends boolean = true> {
  label?: T;
  logos?:
    | T
    | {
        name?: T;
        logo?:
          | T
          | {
              media?: T;
              placeholder?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GartnerCalloutBlock_select".
 */
export interface GartnerCalloutBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lead?: T;
  linkLabel?: T;
  linkHref?: T;
  cards?:
    | T
    | {
        title?: T;
        subtitle?: T;
        meta?: T;
        id?: T;
      };
  peerInsights?:
    | T
    | {
        score?: T;
        source?: T;
        quote?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        linkLabel?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ValuePropsBlock_select".
 */
export interface ValuePropsBlockSelect<T extends boolean = true> {
  layout?: T;
  eyebrow?: T;
  heading?: T;
  lead?: T;
  image?:
    | T
    | {
        media?: T;
        placeholder?: T;
      };
  items?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock_select".
 */
export interface TestimonialBlockSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  org?: T;
  portrait?:
    | T
    | {
        media?: T;
        placeholder?: T;
      };
  videoStill?:
    | T
    | {
        media?: T;
        placeholder?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyCardsBlock_select".
 */
export interface CaseStudyCardsBlockSelect<T extends boolean = true> {
  heading?: T;
  caseStudies?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyArchiveBlock_select".
 */
export interface CaseStudyArchiveBlockSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonTableBlock_select".
 */
export interface ComparisonTableBlockSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  note?: T;
  vendors?:
    | T
    | {
        name?: T;
        highlighted?: T;
        id?: T;
      };
  rows?:
    | T
    | {
        capability?: T;
        cells?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingTableBlock_select".
 */
export interface PricingTableBlockSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  note?: T;
  tiers?:
    | T
    | {
        name?: T;
        description?: T;
        emphasized?: T;
        tabLabel?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABannerBlock_select".
 */
export interface CTABannerBlockSelect<T extends boolean = true> {
  background?: T;
  heading?: T;
  text?: T;
  ctaLabel?: T;
  ctaHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResourceGridBlock_select".
 */
export interface ResourceGridBlockSelect<T extends boolean = true> {
  heading?: T;
  showFilters?: T;
  items?:
    | T
    | {
        resourceType?: T;
        title?: T;
        summary?: T;
        meta?: T;
        featured?: T;
        image?:
          | T
          | {
              media?: T;
              placeholder?: T;
            };
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlockBlock_select".
 */
export interface FormBlockBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lead?: T;
  expectations?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sideQuote?: T;
  formFields?:
    | T
    | {
        label?: T;
        name?: T;
        fieldType?: T;
        options?:
          | T
          | {
              value?: T;
              id?: T;
            };
        required?: T;
        width?: T;
        id?: T;
      };
  submitLabel?: T;
  privacyNote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  audiences?: T;
  postType?: T;
  publishedAt?: T;
  author?: T;
  summary?: T;
  image?:
    | T
    | {
        media?: T;
        placeholder?: T;
      };
  meta?:
    | T
    | {
        readTime?: T;
        duration?: T;
        onDemand?: T;
      };
  featured?: T;
  body?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs_select".
 */
export interface DocsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  categoryPath?: T;
  category?: T;
  order?: T;
  audiences?: T;
  appliesTo?: T;
  excerpt?: T;
  searchText?: T;
  body?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  order?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  logo?:
    | T
    | {
        media?: T;
        placeholder?: T;
      };
  partnerType?: T;
  tier?: T;
  region?: T;
  industries?: T;
  blurb?: T;
  description?: T;
  website?: T;
  contactEmail?: T;
  services?:
    | T
    | {
        name?: T;
        scope?: T;
        id?: T;
      };
  atAGlance?:
    | T
    | {
        certifiedConsultants?: T;
        partnerSince?: T;
        languages?: T;
      };
  quote?:
    | T
    | {
        text?: T;
        attribution?: T;
      };
  integrations?: T;
  caseStudies?: T;
  supportedCustomers?:
    | T
    | {
        customerName?: T;
        supportLevelSold?: T;
        zohoAccountId?: T;
        id?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  logo?:
    | T
    | {
        media?: T;
        placeholder?: T;
      };
  builtBy?: T;
  partner?: T;
  status?: T;
  expectedAvailability?: T;
  category?: T;
  summary?: T;
  docsUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  formName?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}